"""initial schema

Revision ID: 159a3ecc4f74
Revises: 
Create Date: 2026-06-03 11:45:54.464465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '159a3ecc4f74'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('account_id', sa.String(), nullable=True),
    sa.Column('account_name', sa.String(), nullable=True),
    sa.Column('access_token', sa.String(), nullable=True),
    sa.Column('refresh_token', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('available_accounts', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('selected_account_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('last_sync_status', sa.String(), nullable=True),
    sa.Column('last_sync_job_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('connections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_connections_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_connections_user_id'), ['user_id'], unique=False)

    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_user_id'), ['user_id'], unique=False)

    op.create_table('optimization_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('connection_id', sa.Integer(), nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('campaign_name', sa.String(), nullable=True),
    sa.Column('ad_group_name', sa.String(), nullable=True),
    sa.Column('change_type', sa.String(), nullable=True),
    sa.Column('original_value', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('proposed_value', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('is_automated', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('optimization_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_optimization_plans_connection_id'), ['connection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_optimization_plans_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_optimization_plans_user_id'), ['user_id'], unique=False)

    op.create_table('optimization_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('change_type', sa.String(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('optimization_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_optimization_rules_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_optimization_rules_user_id'), ['user_id'], unique=False)

    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('chart_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('scorecards', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('scorecard_deltas', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('platform_deltas', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('comparison_type', sa.String(), nullable=True),
    sa.Column('current_period_label', sa.String(), nullable=True),
    sa.Column('prior_period_label', sa.String(), nullable=True),
    sa.Column('campaign_summary', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('hierarchy_summary', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('platform_summary', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('top_performer', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('bottom_performer', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('gemini_analysis', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_user_id'), ['user_id'], unique=False)

    op.create_table('sync_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('connection_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('progress_percent', sa.Integer(), nullable=True),
    sa.Column('current_step', sa.String(), nullable=True),
    sa.Column('total_steps', sa.Integer(), nullable=True),
    sa.Column('accounts_synced', sa.Integer(), nullable=True),
    sa.Column('total_accounts', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('logs', sa.Text(), nullable=True),
    sa.Column('report_id', sa.Integer(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('max_retries', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sync_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_jobs_connection_id'), ['connection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_jobs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_jobs_user_id'), ['user_id'], unique=False)

    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('google_chat_webhook', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_settings_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_settings_user_id'), ['user_id'], unique=True)

    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('tool_name', sa.String(), nullable=True),
    sa.Column('tool_call_id', sa.String(), nullable=True),
    sa.Column('tool_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_id'))
        batch_op.drop_index(batch_op.f('ix_messages_conversation_id'))

    op.drop_table('messages')
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_settings_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_settings_id'))

    op.drop_table('user_settings')
    with op.batch_alter_table('sync_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_jobs_user_id'))
        batch_op.drop_index(batch_op.f('ix_sync_jobs_id'))
        batch_op.drop_index(batch_op.f('ix_sync_jobs_connection_id'))

    op.drop_table('sync_jobs')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_user_id'))
        batch_op.drop_index(batch_op.f('ix_reports_id'))

    op.drop_table('reports')
    with op.batch_alter_table('optimization_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_optimization_rules_user_id'))
        batch_op.drop_index(batch_op.f('ix_optimization_rules_id'))

    op.drop_table('optimization_rules')
    with op.batch_alter_table('optimization_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_optimization_plans_user_id'))
        batch_op.drop_index(batch_op.f('ix_optimization_plans_id'))
        batch_op.drop_index(batch_op.f('ix_optimization_plans_connection_id'))

    op.drop_table('optimization_plans')
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversations_user_id'))
        batch_op.drop_index(batch_op.f('ix_conversations_id'))

    op.drop_table('conversations')
    with op.batch_alter_table('connections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_connections_user_id'))
        batch_op.drop_index(batch_op.f('ix_connections_id'))

    op.drop_table('connections')
    # ### end Alembic commands ###
